[package]
name = "deadpool-postgres"
version = "0.6.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool for tokio-postgres"
keywords = ["async", "database", "pool", "postgres"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
deadpool = { path = "../", version = "0.6.0", default-features = false, features = ["managed"] }
async-trait = "0.1.17"
futures = "0.3.1"
log = "0.4"
tokio = { version = "0.2", features = ["sync", "rt-threaded"] }
tokio-postgres = "0.5"
# only required when using the config feature
config-crate = { package = "config", version = "0.10.1", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true}

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[features]
default = ["config"]
config = ["config-crate", "serde", "deadpool/config"]
